package common

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

// PluginInfo contains metadata about a protobuf plugin
type PluginInfo struct {
	Name        string
	Version     string
	Description string
}

// GeneratorConfig holds configuration for code generation
type GeneratorConfig struct {
	Plugin      PluginInfo
	PackageName string
	Imports     []string
}

// CodeGenerator provides common functionality for protobuf plugins
type CodeGenerator struct {
	config *GeneratorConfig
	gen    *protogen.Plugin
}

// NewCodeGenerator creates a new code generator
func NewCodeGenerator(config *GeneratorConfig, gen *protogen.Plugin) *CodeGenerator {
	return &CodeGenerator{
		config: config,
		gen:    gen,
	}
}

// GenerateHeader generates standard file header with imports
func (cg *CodeGenerator) GenerateHeader(g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by ", cg.config.Plugin.Name, ". DO NOT EDIT.")
	g.P("// versions:")
	g.P("// \t", cg.config.Plugin.Name, " ", cg.config.Plugin.Version)
	g.P("// \tsource: ", file.Desc.Path())
	g.P()
	g.P("package ", cg.config.PackageName)
	g.P()

	if len(cg.config.Imports) > 0 {
		g.P("import (")
		for _, imp := range cg.config.Imports {
			g.P("\t", imp)
		}
		g.P(")")
		g.P()
	}
}

// ServiceInfo contains information about a protobuf service
type ServiceInfo struct {
	Name        string
	GoName      string
	Description string
	Methods     []*MethodInfo
}

// MethodInfo contains information about a service method
type MethodInfo struct {
	Name        string
	GoName      string
	Description string
	InputType   string
	OutputType  string
	HTTPMethod  string
	HTTPPath    string
	Tag         string
	Summary     string
	Deprecated  bool
	Annotations *RESTAnnotation
}

// ExtractServiceInfo extracts service information from protogen.Service
func (cg *CodeGenerator) ExtractServiceInfo(service *protogen.Service) *ServiceInfo {
	serviceInfo := &ServiceInfo{
		Name:        string(service.Desc.Name()),
		GoName:      service.GoName,
		Description: ExtractCommentDescription(string(service.Comments.Leading)),
		Methods:     make([]*MethodInfo, 0, len(service.Methods)),
	}

	if serviceInfo.Description == "" {
		serviceInfo.Description = fmt.Sprintf("%s service", serviceInfo.GoName)
	}

	for _, method := range service.Methods {
		// Extract REST annotations from method options and comments using complete annotation parser
		annotations := ExtractCompleteAnnotations(method)

		// Validate the complete annotation
		ValidateCompleteAnnotation(annotations)

		methodInfo := &MethodInfo{
			Name:        string(method.Desc.Name()),
			GoName:      method.GoName,
			Description: annotations.Description,
			InputType:   method.Input.GoIdent.GoName,
			OutputType:  method.Output.GoIdent.GoName,
			HTTPMethod:  annotations.Method,
			HTTPPath:    annotations.Path,
			Tag:         annotations.Tag,
			Summary:     annotations.Summary,
			Deprecated:  annotations.Deprecated,
			Annotations: annotations,
		}

		if methodInfo.Description == "" {
			methodInfo.Description = fmt.Sprintf("%s method in %s service", methodInfo.GoName, serviceInfo.GoName)
		}
		if methodInfo.Summary == "" {
			methodInfo.Summary = methodInfo.Description
		}

		serviceInfo.Methods = append(serviceInfo.Methods, methodInfo)
	}

	return serviceInfo
}

// GetOutputFilename generates output filename for a proto file
func (cg *CodeGenerator) GetOutputFilename(file *protogen.File, suffix string) string {
	return file.GeneratedFilenamePrefix + suffix
}

// ShouldGenerateForFile checks if code should be generated for a file
func (cg *CodeGenerator) ShouldGenerateForFile(file *protogen.File) bool {
	return file.Generate && len(file.Services) > 0
}